
name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          # Subject updates automatically
          subject: >
            GitHub Notification -
            ${{ github.event_name == 'pull_request' && 'New Pull Request' || 'New Push' }}

          # 👇 IF push → send to committer
          # 👇 IF PR → send to team
          to: >
            ${{ github.event_name == 'push'
                && github.event.head_commit.author.email
                || 'team@example.com' }}

          from: "GitHub CI <${{ secrets.EMAIL_USERNAME }}>"

          body: |
            Event   : ${{ github.event_name }}
            Branch  : ${{ github.ref }}
            Commit  : ${{ github.sha }}
            Actor   : ${{ github.actor }}

            # For Push
            Committer Email : ${{ github.event.head_commit.author.email }}
            Commit Message  : ${{ github.event.head_commit.message }}

            # For PR
            PR Title  : ${{ github.event.pull_request.title }}
            PR URL    : ${{ github.event.pull_request.html_url }}
